---
title: 'STAT 663: Final Project(NISS Visualization Competition)'
author: 'Group 2'
date: "4/10/2022"
output: 
  html_document:
    theme: united
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message = F, warning = F}
library(tidyr)
library(plotly)
library(dplyr)

library(tidyverse)
library(geojsonio)
library(leaflet)
library(maps)
library(sp)
library(rgeos)
library(htmlwidgets)
library(lubridate)
library(rgdal)
```

```{r}
#reading in excel files
hs_comp <- read.csv("table_603.10.byAges.csv", header = TRUE)
college_comp <- read.csv("table_603.20.byAges.csv", header = TRUE)

#trimming whitespace after country name
hs_comp$Country <- trimws(hs_comp$Country, which = c("right"))
college_comp$Country <- trimws(hs_comp$Country, which = c("right"))

#transforming data to tibble
hs_comp <- as_tibble(hs_comp)
college_comp <- as_tibble(college_comp) 

#Pivoting Data for better readability
age_range <- c("25_64", "25_34")

hs_comp_pop <- hs_comp[,1:8] %>% filter(Ages %in% age_range) %>% 
  pivot_longer(P.2000:P.2019, names_to = "year", names_prefix = "P.", values_to = "pop_percent_hs") 

hs_comp_se <- hs_comp[, c(1:2, 9:12)] %>% filter(Ages %in% age_range) %>% 
  pivot_longer(SE.2010:SE.2019, names_to = "year", names_prefix = "SE.", values_to = "standard_error_hs") 

hs_data <- left_join(hs_comp_pop, hs_comp_se, by = c("Country", "Ages", "year"))

college_comp_pop <- college_comp[, 1:8] %>% filter(Ages %in% age_range) %>% 
  pivot_longer(P.2000:P.2019, names_to = "year", names_prefix = "P.", values_to = "pop_percent_college") 

college_comp_se <-college_comp[, c(1:2, 9:12)] %>% filter(Ages %in% age_range) %>% 
  pivot_longer(SE.2010:SE.2019, names_to = "year", names_prefix = "SE.", values_to = "standard_error_college")

college_data <- left_join(college_comp_pop, college_comp_se, by = c("Country", "Ages", "year"))

#combining high school and college data into single data frame
new_data <- full_join(hs_data, college_data)
head(new_data)

new_data2 <- new_data
```

```{r}
#replaced NA values for hs population percentage and college to 0 so that
#postsecondary data appears better in plotly visual
new_data$pop_percent_hs[is.na(new_data$pop_percent_hs)] <- 0
new_data$pop_percent_college[is.na(new_data$pop_percent_college)] <- 0
```

```{r}
###############################CREATING VISUALS#################################

vis_data <- new_data[, c(1:4,6)] %>%
  pivot_longer(pop_percent_hs:pop_percent_college, #improved dataset for visuals
               names_to = "percentage_name"  , values_to = "percentages") %>% 
  unite(age_percent, c(Ages, percentage_name))

attach(vis_data)

country_names <- unique(new_data$Country)
visuals = list()

for(i in country_names){
  #creating base for visualization
  f <- vis_data %>% filter(Country == i) %>% plot_ly() %>%  
    add_bars(x = ~unique(year), y = ~percentages[age_percent == "25_64_pop_percent_hs"],
             name = ~"High School Completion (Ages 25-64)") %>%
    
    add_bars(x = ~unique(year), y = ~percentages[age_percent == "25_64_pop_percent_college"],
             name = ~"Post Secondary Degree (Ages 25-64)") %>%
    
    add_bars(x = ~unique(year), y = ~percentages[age_percent == "25_34_pop_percent_hs"],
             name = ~"High School Completion (Ages 25-34)", color = I("seagreen3")) %>%
    
    add_bars(x = ~unique(year), y = ~percentages[age_percent == "25_34_pop_percent_college"],
             name = ~"Post Secondary Degree (Ages 25-34)", color = I("orchid")) %>%
    
    add_trace(data = vis_data[1:12,], x = ~unique(year), 
              y = ~percentages[age_percent == "25_64_pop_percent_hs"],
              name = ~"OECD Average Percent for High School Completion",
              type = "scatter", mode = "lines+markers",
              line = list(width = 3, color = "black"), visible = F) %>%
    
    add_trace(data = vis_data[1:12,], x = ~unique(year),
              y = ~percentages[age_percent == "25_64_pop_percent_college"],
              name = ~"OECD Average Percent for Post Secondary Degree",
              type = "scatter", mode = "lines+markers", 
              line = list(width = 3, color = "black", dash = "dash"), visible = F) %>%
    
    add_trace(data = vis_data[481:492,], x = ~unique(year), 
              y = ~percentages[age_percent == "25_34_pop_percent_hs"],
              name = ~"OECD Average Percent for High School Completion",
              type = "scatter", mode = "lines+markers",
              line = list(width = 3, color = "red"), visible = F) %>%
    
    add_trace(data = vis_data[481:492,], x = ~unique(year),
              y = ~percentages[age_percent == "25_34_pop_percent_college"],
              name = ~"OECD Average Percent for Post Secondary Degree",
              type = "scatter", mode = "lines+markers", 
              line = list(width = 3, color = "red", dash = "dash"), visible = F)
  
  #adjusting layouts based on dropdown selection
  
  f <- f %>% layout(xaxis = list(title = "year"), 
                     yaxis = list(title = "population percentage"),
                     title = "% of population that completed High School vs Postsecondary Education by Age Group",
                     updatemenus = list(
                       list(
                         type = "dropdown",
                         active = 0,
                         x = 1.2,
                         xanchor = "right",
                         y = 0.60,
                         yanchor = "middle",
                         buttons = list(
                           list(method =  "restyle", 
                                args = list("visible", list(TRUE, TRUE, TRUE, TRUE, FALSE, FALSE,FALSE, FALSE)),
                                label = "All Age Ranges"),
                          
                           list(method =  "restyle",
                                args = list("visible", list(TRUE, TRUE, FALSE, FALSE, TRUE, TRUE,FALSE, FALSE)),
                                label = "Ages 25 to 64"),
                          
                           list(method = "restyle",
                                args = list("visible", list(FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE)),
                                label = "Ages 25 to 34")
                           )
                         )
                       )
                     )
  
  visuals[[i]] = f
}

visuals$Chile #visual output
```


```{r}
#download the world spatial df 
#download.file("http://thematicmapping.org/downloads/TM_WORLD_BORDERS_SIMPL-0.3.zip"
  #            , destfile="DATA/world_shape_file.zip")

# Unzip this file. You can do it with R (as below), or clicking on the object you downloaded.
#unzip("DATA/world_shape_file.zip")


# Read this shape file with the rgdal library. 
world_spdf <- readOGR( 
  dsn= "DATA/world_shape_file", 
  layer="TM_WORLD_BORDERS_SIMPL-0.3",
  verbose=FALSE
)

# Clean the data object
world_spdf@data$POP2005[ which(world_spdf@data$POP2005 == 0)] = NA
world_spdf@data$POP2005 <- as.numeric(as.character(world_spdf@data$POP2005)) / 1000000 %>% round(2)

#show the world spatial data
#world_spdf@data

#joining the world spatial df with the new_data and select only relevant columns
data.spatial <- sp::merge(world_spdf, new_data2, by.x='NAME',by.y='Country',  duplicateGeoms = TRUE)

#setdiff(world_spdf@data$NAME, new_data$Country)
```


```{r}
#create a function for drawing the map
map.draw <- function(dat, fill.var, labels, pal, ID){
  dmap <- leaflet(dat) %>%
    setView(lat=55.378052, lng=-3.435973, zoom=2) %>%
    addTiles() %>%
    addPolygons(fillColor = ~pal(dat@data %>% pull(fill.var)), weight = 1, 
                opacity = 1, color = "white", dashArray = "3", fillOpacity = 0.9, 
                layerId = ~dat@data %>% pull(ID), 
                highlight = highlightOptions(weight = 5, color = "#666", dashArray = "", 
                                             fillOpacity = 0.9, bringToFront = TRUE), 
                label = labels,
                labelOptions = labelOptions(style = list("font-weight" = "normal", padding = "3px 8px"), 
                                            textsize = "15px", direction = "auto")) %>%
    addLegend(pal = pal, values = ~dat@data %>% pull(fill.var), opacity = 0.7, 
              title = NULL, position = "bottomright") 
}

#create the label
labels_country <- sprintf(
  "<strong>%s</strong><br/>Percentage of highschool completion: %g<br>
  Percentage of postsecondary diploma completion: %g",
  data.spatial$NAME, round(data.spatial$pop_percent_hs, 2), 
  round(data.spatial$pop_percent_college, 2)) %>% 
  lapply(htmltools::HTML)

#drawing the map
pal.country.quantile <- colorQuantile(palette = "YlOrRd", domain = data.spatial$pop_percent_hs, n=8)
fig<-map.draw(dat = data.spatial, fill.var = 'pop_percent_hs', labels = labels_country, 
                pal = pal.country.quantile, ID = 'NAME')

fig

#save the figure
saveWidget(fig, "fig.html", selfcontained = FALSE)

```



# In this part, I'm trying to create trend lines of countries in each continent...
```{r}
#To create trend lines of countries in each continent
#Create new variable of "Continent"

vis_data2 <- new_data2[, c(1:4,6)] %>%
  pivot_longer(pop_percent_hs:pop_percent_college, #improved dataset for visuals
               names_to = "percentage_name"  , values_to = "percentages") %>% 
  unite(age_percent, c(Ages, percentage_name))

Asia <- c("Israel", "Japan", "Korea, Republic of", "Turkey", "China", "Russia")
Australia <- c("Australia", "New Zealand")
Europe <- c("Austria", "Belgium", "Czech Republic", "Denmark", "Estonia", "Finland", 
            "France", "Germany", "Greece", "Hungary", "Iceland", "Ireland", "Italy", 
            "Latvia", "Lithuania", "Luxembourg", "Netherlands", "Norway", "Poland", 
            "Portugal", "Slovakia", "Slovenia", "Spain", "Sweden", "Switzerland", 
            "United Kingdom")
NorthAmerica <- c("Canada", "Mexico", "United States")
SouthAmerica <- c("Chile", "Colombia")

continent.f1 <- function(x) {replace(vis_data2$Continent, x %in% Asia, "Asia")}
continent.f2 <- function(x) {replace(vis_data2$Continent, x %in% Australia, "Australia")}
continent.f3 <- function(x) {replace(vis_data2$Continent, x %in% Europe, "Europe")}
continent.f4 <- function(x) {replace(vis_data2$Continent, x %in% NorthAmerica, "NorthAmerica")}
continent.f5 <- function(x) {replace(vis_data2$Continent, x %in% SouthAmerica, "SouthAmerica")}

vis_data2 <- vis_data2 %>% mutate(Continent = Country) 
vis_data2 <- vis_data2 %>% mutate_at(c("Continent"), continent.f1) 
vis_data2 <- vis_data2 %>% mutate_at(c("Continent"), continent.f2) 
vis_data2 <- vis_data2 %>% mutate_at(c("Continent"), continent.f3) 
vis_data2 <- vis_data2 %>% mutate_at(c("Continent"), continent.f4) 
vis_data2 <- vis_data2 %>% mutate_at(c("Continent"), continent.f5) 
```











